backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow
media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "clanky"
    label: "Články"
    folder: "data/clanky"
    create: true
    slug: "{{year}}-{{month}}-{{slug}}"
    fields:
      - {label: "Titulek", name: "title", widget: "string"}
      - {label: "Datum", name: "date", widget: "datetime"}
      - {label: "GPU Náročnost (3D prvky)", name: "gpu_narocnost", widget: "boolean", default: false}
      - {label: "Obsah", name: "body", widget: "markdown"}
      
